name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username '${{ secrets.DOCKER_USERNAME }}' --password-stdin
    - run: |
        export VERSION="${GITHUB_REF/refs\/tags\//}"
        make publish OS=linux CPU=amd64
